osql -S %1 -d %2 -E  -e -i ".\3.- Funciones\1.-Fn_Busca_DireccionMac.sql"               > mgrFunciones.log
osql -S %1 -d %2 -E  -e -i ".\3.- Funciones\2.-Fn_Busca_MensajeError.sql"              >> mgrFunciones.log
osql -S %1 -d %2 -E  -e -i ".\3.- Funciones\3.-Fn_BuscaDescripcionCriterio.sql"        >> mgrFunciones.log
osql -S %1 -d %2 -E  -e -i ".\3.- Funciones\4.-Fn_BuscaDescripcionGeneral.sql"         >> mgrFunciones.log
osql -S %1 -d %2 -E  -e -i ".\3.- Funciones\5.-Fn_BuscaDireccionIP.sql"                >> mgrFunciones.log
osql -S %1 -d %2 -E  -e -i ".\3.- Funciones\6.-Fn_BuscaValorParametro.sql"             >> mgrFunciones.log
osql -S %1 -d %2 -E  -e -i ".\3.- Funciones\7.-Fn_ConvierteNumeroLetra.sql"            >> mgrFunciones.log
osql -S %1 -d %2 -E  -e -i ".\3.- Funciones\8.-Fn_Desencripta_cadena.sql"              >> mgrFunciones.log
osql -S %1 -d %2 -E  -e -i ".\3.- Funciones\9.-Fn_Encripta_cadena.sql"                 >> mgrFunciones.log
osql -S %1 -d %2 -E  -e -i ".\3.- Funciones\10.-Fn_existe_tabla.sql"                   >> mgrFunciones.log
osql -S %1 -d %2 -E  -e -i ".\3.- Funciones\11.-Fn_GeneraNombreTablaDin.sql"           >> mgrFunciones.log
osql -S %1 -d %2 -E  -e -i ".\3.- Funciones\12.-Fn_splitStringColumna.sql"             >> mgrFunciones.log
osql -S %1 -d %2 -E  -e -i ".\3.- Funciones\13.-Fn_BuscaMes.sql"                       >> mgrFunciones.log
osql -S %1 -d %2 -E  -e -i ".\3.- Funciones\14.-Fn_ValidaCorreo.sql"                   >> mgrFunciones.log
osql -S %1 -d %2 -E  -e -i ".\3.- Funciones\15.-Fn_ValidaAnioBisiesto.sql"             >> mgrFunciones.log
osql -S %1 -d %2 -E  -e -i ".\3.- Funciones\16.-Fn_BuscaValoresCriterio.sql"           >> mgrFunciones.log
osql -S %1 -d %2 -E  -e -i ".\3.- Funciones\17.-Fn_BuscaNombrePais.sql"                >> mgrFunciones.log
osql -S %1 -d %2 -E  -e -i ".\3.- Funciones\18.-Fn_BuscaNombreEstado.sql"              >> mgrFunciones.log
osql -S %1 -d %2 -E  -e -i ".\3.- Funciones\19.-Fn_BuscaNombreMunicipio.sql"           >> mgrFunciones.log
osql -S %1 -d %2 -E  -e -i ".\3.- Funciones\20.-Fn_BuscaNombreCiudad.sql"              >> mgrFunciones.log
osql -S %1 -d %2 -E  -e -i ".\3.- Funciones\21.-Fn_BuscaNombreColonia.sql"             >> mgrFunciones.log
osql -S %1 -d %2 -E  -e -i ".\3.- Funciones\22.-Fn_BuscaResultadosParametros.sql"      >> mgrFunciones.log

osql -S %1 -d Ejercicio_DES -E  -e -i ".\3.- Funciones\10.-Fn_existe_tabla.sql"        >> mgrFunciones.log
osql -S %1 -d DB_GEN_DES    -E  -e -i ".\3.- Funciones\10.-Fn_existe_tabla.sql"        >> mgrFunciones.log
